apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  links:
    - url: https://www.youtube.com/
      title: Youtube
      icon: dashboard
      type: youtubedashboard
  description: An example service for learning Backstage
  tags:
    - web
    - backend
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: examples
  
