apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: An example service for learning Backstage
  tags:
    - web
    - backend
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: examples
  
