apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-database
  description: Database for the example service
spec:
  type: database
  lifecycle: experimental
  owner: user:guest
  system: examples